services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:24
    user: node
    ports:
      # "ホスト側のポート: - デフォルト値 :{コンテナ側のポート}"
      - "${APP_PORT:-3000}:3000"
      - "${DRIZZLE_PORT:-4983}:4983"
      - "${WRANGLER_PORT:-8787}:8787"
    volumes:
      - ..:/workspaces/app:cached
    working_dir: /workspaces/app

    command: sleep infinity
